This notebook merges the SNPP and NOAA-20 VIIRS detections

In [1]:
import pandas as pd
#pd.set_option("display.max_rows", None, "display.max_columns", None)
from datetime import datetime, timedelta

In [2]:
viirs_n20 = pd.read_csv('fire_nrt_J1V-C2_230186.csv')
viirs_snpp = pd.read_csv('fire_archive_SV-C2_230187.csv')
print(viirs_n20.dtypes)
print(viirs_snpp.dtypes)

latitude      float64
longitude     float64
brightness    float64
scan          float64
track         float64
acq_date       object
acq_time        int64
satellite       int64
instrument     object
confidence     object
version        object
bright_t31    float64
frp           float64
daynight       object
dtype: object
latitude      float64
longitude     float64
brightness    float64
scan          float64
track         float64
acq_date       object
acq_time        int64
satellite      object
instrument     object
confidence     object
version         int64
bright_t31    float64
frp           float64
daynight       object
type            int64
dtype: object

In [5]:
print(viirs_n20.shape, viirs_snpp.shape)
viirs_all = pd.concat([viirs_n20, viirs_snpp], axis = 0)
print(viirs_all.shape)
viirs_all.to_csv('merged_viirs.csv', index=False)

(460934, 14) (604433, 15)
(1065367, 15)

In [6]:
viirs_all

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,46.145030,-114.230690,301.50,0.40,0.60,2019-12-04,842,1,VIIRS,n,2.0NRT,266.30,1.30,N,NaN
1,42.689530,-111.592030,309.10,0.55,0.51,2019-12-04,842,1,VIIRS,n,2.0NRT,270.90,8.00,N,NaN
2,47.817650,-103.056590,296.60,0.42,0.38,2019-12-04,842,1,VIIRS,n,2.0NRT,269.20,0.60,N,NaN
3,45.846410,-105.521350,297.80,0.47,0.40,2019-12-04,842,1,VIIRS,n,2.0NRT,272.00,0.80,N,NaN
4,45.842090,-105.516050,306.40,0.47,0.40,2019-12-04,842,1,VIIRS,n,2.0NRT,272.00,2.20,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604428,39.142639,-121.509666,344.93,0.41,0.45,2020-12-31,2124,N,VIIRS,n,1,286.05,6.97,D,0.0
604429,39.143078,-121.504829,328.83,0.41,0.45,2020-12-31,2124,N,VIIRS,n,1,284.42,4.39,D,0.0
604430,38.063091,-121.160683,328.92,0.42,0.45,2020-12-31,2124,N,VIIRS,n,1,282.11,2.19,D,0.0
604431,38.223763,-121.081375,325.87,0.42,0.46,2020-12-31,2124,N,VIIRS,n,1,280.99,2.84,D,0.0
604432,42.285534,-120.333702,338.20,0.51,0.50,2020-12-31,2130,N,VIIRS,n,1,273.02,20.89,D,0.0